name: test

on:
  push:
  pull_request:

jobs:
  bash:
    name: bash on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - run: bash tests/run-tests.sh

  windows-powershell-5:
    name: Windows PowerShell 5.1
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        shell: powershell
        run: ./tests/run-tests.ps1

  powershell-7:
    name: PowerShell 7 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        shell: pwsh
        run: ./tests/run-tests.ps1
